- hosts: localhost
  become: true

  vars:
    username: "nawaz"
    userhome: "/home/{{ username }}"

  tasks:

  - include: tasks/configure-software-ubuntu.yml
    when: ansible_facts["os_family"] == "Debian"
  - include: tasks/configure-xmonad.yml
  - include: tasks/configure-user.yml
