- hosts: localhost
  become: true

  vars:
    username: "nawaz"
    userhome: "/home/{{ username }}"

  tasks:

  - include: tasks/configure-ubuntu.yaml
    when: ansible_facts["os_family"] == "Debian"
  - include: tasks/configure-xmonad.yaml
  - include: tasks/configure-user.yaml
