- name: Package Installation - Update Apt package cache
  apt:
    update_cache: true
  changed_when: false

- name: Package Installation - Productivity Tools
  package:
    name: [
        'gnome-terminal',
        'pcmanfm',
        'fonts-font-awesome',
	'lxappearance',
	'htop',
	'qalculate-gtk'
    ]
    state: present

- name: Package Installation - Development Tools
  package:
    name: [
        'binutils',
	'build-essential',
	'gcc'
    ]
    state: present

- name: Package Installation - Media
  package:
    name: [
        'mpv',
        'vlc'
    ]
    state: present

- name: Package Installation - System Desktop
  package:
    name: [
        'nitrogen',
        'xmobar'
    ]
    state: present
